#!/usr/bin/env node

/* Copyright © 2017 Ganchrow Scientific, SA all rights reserved */
'use strict';

let path = require('path');

let packagePath = path.resolve(process.argv[2]);
let property = path.resolve(process.argv[3]);

let packageVersion = require(`${packagePath}/package.json`)[property];

console.log(packageVersion);
